name = "first-webpack"
type = "webpack"
account_id = "664dd4790d298e6a2e2fddf03b4bc181"
workers_dev = true
route = "https://webpack.nginxme.com/*"

zone_id = "7ad1099bafa753bcba19d290930eadf2"
webpack_config = "webpack.config.js"

[[kv_namespaces]]
binding = "FILES"
id = "f68cc5c9c44c4b35a8252c042f614d0c"